# Generated by Django 5.0.7 on 2024-07-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
