# Generated by Django 5.0.7 on 2024-07-25 08:51

import record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=record.models.upload_filepath),
        ),
    ]
