# Generated by Django 5.0.7 on 2024-07-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_audiofile_alter_follow_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='file',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='audio_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
